export const GET_ADDRESS_SIDO = 'GET-ADDRESS-SIDO';
export const GET_ADDRESS_SIDO_SIGUNGU = 'GET-ADDRESS-SIDO-SIGUNGU';
export const GET_ADDRESS_SIDO_SIGUNGU_JUSO = 'GET-ADDRESS-SIDO-SIGUNGU-JUSO';
export const GET_ADDRESS_SIDO_SIGUNGU_DONG_OF_ADMIN = 'GET-ADDRESS-SIDO-SIGUNGU-DONG-OF-ADMIN';
export const GET_ADDRESS_JUSO = 'GET-ADDRESS-JUSO';
export const POST_ADDRESS_SELECT = 'POST-ADDRESS-SELECT';
export const GET_ADDRESS_CONVERSION = 'GET-ADGDRESS-CONVERSION';